### ISSUE TITLE
Nouveau site en cours - Next 

### ISSUE THREAD

**Issue by floviolleau** [AnaelMobilia/NextINpact-Unofficial#309]
Bonjour,

Un grand merci pour cette super application que j'utilise tous les jours beaucoup plus pratique en déplacement sans connexion internet que leur site mobile.

Next INPact deviendra bientôt Next. Est-il prévu que l'application soit adaptée pour fonctionner avec le nouveau site (qui sera du Wordpress) ?

Pour info : https://beta.next.ink

Merci !

**Comment by AnaelMobilia** [comment]
Bonjour @floviolleau ,

C'est bien prévu, j'attends de voir la bêta de l'outil pour adapter la récupération de contenu !

Bonne journée,
Anael

**Comment by AnaelMobilia** [comment]
- [ ] Récupération du contenu des articles
- [ ] Récupération des auteurs (table tierce à prévoir)
- [ ] Récupération du nombre de commentaires
- [ ] Gestion de la mise à jour de l'article (ex : 116807)
- [ ] Récupération des commentaires

**Comment by AnaelMobilia** [comment]
Suite à la mise en ligne de la version finale de Next, voici les éléments qui ont manquent :
- [ ] Statut abonné d'un article (le plugin "acf" est à nouveau vide - était lié à https://github.com/NextINpact/Next/issues/82)
- [ ] Accès à l'auteur d'un commentaire https://github.com/NextINpact/Next/issues/99
- [ ] Accès au contenu abonné des articles https://github.com/NextINpact/Next/issues/100

**Comment by AnaelMobilia** [comment]
L'équipe de Next n'ayant pas encore réussi à finaliser / stabiliser les API, la version 2.7.2 de l'application va parser directement le site web pour la partie abonné (au lieu d'utiliser l'API).

Quand l'API sera fonctionnelle pour ce point là, je repasserai l'application dessus.

Du coup, avec la v2.7.2, le contenu abonné est récupéré ! :-)

**Comment by AnaelMobilia** [comment]
L'ensemble des éléments est désormais présent => clôture de l'issue :)
